package paquete;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lbecerrils
 */
public class ClasificadorP extends javax.swing.JFrame {
    DefaultTableModel md;
    String data [][] ={};
    String cabeza []={"Subclase","Cardinalidad"};
    int Ctotal=0;
    public ClasificadorP(String NameC,int Ctotal) {

        initComponents();
              this.Ctotal=Ctotal;
              TextoS.setText(""+Ctotal);
              TextoS.setEditable(false);
              Actualizar.setEnabled(false);
              setTitle("Clase "+NameC);
              setVisible(true);
              setResizable(false);
              setSize(650,450);
              setLocation(150,150);
              Nameclass.setText("         Clase "+NameC);
              md =new DefaultTableModel(data,cabeza);
              jtbldatos.setModel(md);         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Namdeadd = new javax.swing.JLabel();
        TextoNameClass = new javax.swing.JTextField();
        TextoS = new javax.swing.JTextField();
        TextoCardinamidad = new javax.swing.JTextField();
        Nameclass = new javax.swing.JLabel();
        S = new javax.swing.JLabel();
        Cardinalidad1 = new javax.swing.JLabel();
        SendData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbldatos = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Anima = new javax.swing.JLabel();
        Mayor = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Cambiar = new javax.swing.JButton();
        FondoB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Namdeadd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Namdeadd.setText("Nombre subclase");
        getContentPane().add(Namdeadd);
        Namdeadd.setBounds(20, 70, 100, 20);

        TextoNameClass.setToolTipText("Nombre de la subclase");
        TextoNameClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(TextoNameClass);
        TextoNameClass.setBounds(130, 70, 130, 20);

        TextoS.setToolTipText("Nombre de la subclase");
        TextoS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(TextoS);
        TextoS.setBounds(460, 70, 60, 20);

        TextoCardinamidad.setToolTipText("Cardinalidad de la subclase");
        TextoCardinamidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(TextoCardinamidad);
        TextoCardinamidad.setBounds(130, 100, 130, 20);

        Nameclass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(Nameclass);
        Nameclass.setBounds(210, 10, 230, 30);

        S.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        S.setText("Cardinalidad total");
        getContentPane().add(S);
        S.setBounds(350, 70, 100, 20);

        Cardinalidad1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Cardinalidad1.setText("Cardinalidad");
        getContentPane().add(Cardinalidad1);
        Cardinalidad1.setBounds(20, 100, 80, 20);

        SendData.setText("Guardar");
        SendData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendDataActionPerformed(evt);
            }
        });
        getContentPane().add(SendData);
        SendData.setBounds(20, 140, 90, 23);

        jtbldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subclase", "S"
            }
        ));
        jtbldatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbldatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbldatos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 180, 330, 230);

        Delete.setText("Eliminar");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(240, 140, 110, 23);

        Update.setText("Actualizar");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(120, 140, 110, 23);

        Anima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Aninamcion.gif"))); // NOI18N
        getContentPane().add(Anima);
        Anima.setBounds(460, 190, 160, 170);

        Mayor.setText("Ocurrencia mayor");
        Mayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayorActionPerformed(evt);
            }
        });
        getContentPane().add(Mayor);
        Mayor.setBounds(360, 140, 270, 23);

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actuaizar(evt);
            }
        });
        getContentPane().add(Actualizar);
        Actualizar.setBounds(530, 100, 100, 23);

        Cambiar.setText("Cambiar");
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cambiar(evt);
            }
        });
        getContentPane().add(Cambiar);
        Cambiar.setBounds(530, 70, 100, 23);

        FondoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FondoB.png"))); // NOI18N
        getContentPane().add(FondoB);
        FondoB.setBounds(0, 0, 660, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendDataActionPerformed
        Agregar();
    }//GEN-LAST:event_SendDataActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        
        if(jtbldatos.getRowCount()==0)
        {
        JOptionPane.showMessageDialog(null,"No hay información y/o no haz seleccionado ninguna subclase para eliminar");
        }
        else
        Eliminar();
    }//GEN-LAST:event_DeleteActionPerformed

    private void jtbldatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbldatosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getButton()==1){SetValues();}
        if(evt.getButton()==3)
        {
            String aux = (String)(md.getValueAt(jtbldatos.getSelectedRow(),0));
            JOptionPane.showMessageDialog(null," La ocurrencia de la clase '"+aux+"' es: "+GetProbability()*100+"%");
        }
    }//GEN-LAST:event_jtbldatosMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        
        int fila=jtbldatos.getSelectedRow();
        String aux=(String)(md.getValueAt(fila,1));
        int auxvalor=Integer.parseInt(aux);
        int cardinaidadtotal=GetAllCardinalidad();
        int aux2=cardinaidadtotal-auxvalor;
        aux2=aux2+Integer.parseInt(TextoCardinamidad.getText());
        if( TextoNameClass.getText().length()==0 || TextoCardinamidad.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Existe campo(s) vacio(s) y/o no haz seleccionado ninguna subclase");
        }
        else
        {
                    if(aux2<=Ctotal)
                    {
                        Update();
                    }
                    else 
                    {
                        JOptionPane.showMessageDialog(null,"Intenta de nuevo, estas sobrepasando la cardinalidad total: "+Ctotal);
                    }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void MayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayorActionPerformed
        if(jtbldatos.getRowCount()==0)
        {
        JOptionPane.showMessageDialog(null,"No hay información de subclases para determinar la mayor ocurrencia");
        }
        else
        GetMayorProba();
    }//GEN-LAST:event_MayorActionPerformed

    private void Cambiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cambiar
        Cambiar();
    }//GEN-LAST:event_Cambiar

    private void Actuaizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actuaizar
        Actualizar(Integer.parseInt(TextoS.getText()));
    }//GEN-LAST:event_Actuaizar
    
    public void Actualizar(int S)
    {
            int sactual=0;
            sactual=GetAllCardinalidad();
            if(S<sactual)
            {
            JOptionPane.showMessageDialog(null,"Intenta de nuevo, tal vez estas tratando de colocar una cardinalidad (total) menor a la suma de la cardinalidades de las subclases: "+GetAllCardinalidad()+" y se quiere poner un valor menor: "+S);
            }
            else
            {
            Ctotal=S;
            JOptionPane.showMessageDialog(null,"Nueva cardinalidad: "+Ctotal);
            TextoS.setEditable(false);
            Actualizar.setEnabled(false);
            Cambiar.setEnabled(true);
            }
    }
    public void Cambiar()
    {
        Actualizar.setEnabled(true);
        Cambiar.setEnabled(false);
        TextoS.setEditable(true);
    }
    public void Agregar()
    {

        
        if( TextoNameClass.getText().length()==0 || TextoCardinamidad.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Campo(s) vacio(s), intenta de nuevo");
        }
        else 
        {           
                    int aux=0;
                    aux=GetAllCardinalidad()+Integer.parseInt(TextoCardinamidad.getText());
                    if(aux>Ctotal)
                    {
                    JOptionPane.showMessageDialog(null,"Se esta revasando la cardinalidad total de: "+Ctotal);
                    }
                    else{
                    String nombre= TextoNameClass.getText();
                    String cardinalidad=TextoCardinamidad.getText();
                    String datos []={nombre,cardinalidad};
                    md.addRow(datos);
                    TextoNameClass.setText("");
                    TextoCardinamidad.setText("");
                    }
        }
    }
    
    public void Eliminar()
    {   
            int fila=jtbldatos.getSelectedRow();
            md.removeRow(fila);
            TextoNameClass.setText("");
            TextoCardinamidad.setText("");
    }
    
    public void SetValues()
    {
        int fila=jtbldatos.getSelectedRow();
        TextoNameClass.setText((String)(md.getValueAt(fila,0)));
        TextoCardinamidad.setText((String)(md.getValueAt(fila,1)));
    }
    
    public void Update()
    {
                    
                    
            int fila=jtbldatos.getSelectedRow();
            md.setValueAt(TextoNameClass.getText(), fila,0);
            md.setValueAt(TextoCardinamidad.getText(), fila,1);
            TextoNameClass.setText("");
            TextoCardinamidad.setText("");
                    
    }
    
    public int GetAllCardinalidad()
    {
        
          int filas=jtbldatos.getRowCount();
          int Cardinalidatotal=0;
          String aux="";
          
          for(int i=0;i<filas;i++)
          {
             aux=(String)md.getValueAt(i,1);
             Cardinalidatotal=Cardinalidatotal+Integer.parseInt(aux);
          }
        
          return Cardinalidatotal;
          
    }
    
    public float GetProbability()
    {
            int fila=jtbldatos.getSelectedRow();
            float CarIndi=Integer.parseInt((String)md.getValueAt(fila,1));
            float Cardinalidadtotal=GetAllCardinalidad();
            float Proba= CarIndi/Cardinalidadtotal;
            return Proba;
    }
    
    public void GetMayorProba()
    {
            int tam=jtbldatos.getRowCount();
            int arreglo[]=new int[tam];
            for(int i=0; i<tam;i++)
            {
                arreglo[i]=Integer.parseInt((String)md.getValueAt(i,1));
            }
            MayorOMenor mayor=new MayorOMenor();
            
            int numMayor=mayor.GetMayor(arreglo);
            int indexOf=mayor.GetIndexOf(arreglo,mayor.GetMayor(arreglo));
            
            String Cardinalidad=(String)md.getValueAt(indexOf,1);
            String Nombre=(String)md.getValueAt(indexOf,0);
            
            JOptionPane.showMessageDialog(null,"La ocurrencia mayor es de la subclase "+Nombre);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JLabel Anima;
    private javax.swing.JButton Cambiar;
    private javax.swing.JLabel Cardinalidad1;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel FondoB;
    private javax.swing.JButton Mayor;
    private javax.swing.JLabel Namdeadd;
    private javax.swing.JLabel Nameclass;
    private javax.swing.JLabel S;
    private javax.swing.JButton SendData;
    private javax.swing.JTextField TextoCardinamidad;
    private javax.swing.JTextField TextoNameClass;
    private javax.swing.JTextField TextoS;
    private javax.swing.JButton Update;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbldatos;
    // End of variables declaration//GEN-END:variables
}
